DROP TABLE IF EXISTS trip_owners CASCADE;


CREATE TABLE trip_owners (
  id SERIAL PRIMARY KEY NOT NULL,

  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trip_id INTEGER REFERENCES trips(id) ON DELETE CASCADE
)
